### ISSUE TITLE
GDG Spinner: Background and font have no contrast

### ISSUE THREAD

**Issue by stefanhoth** [gdg-x/frisbee#208] opened 2015-02-21 23:27 UTC
Moto X (1st Gen) with Android 4.4.4

![image](https://cloud.githubusercontent.com/assets/45467/6316527/8825fa92-ba29-11e4-9992-2dbdecdcb75d.png)

**Comment by stefanhoth** [comment] 2015-02-21 23:33
Also confirmed for 5.0 with Nexus 6 on Genymotion

![image](https://cloud.githubusercontent.com/assets/45467/6316543/6fadcaac-ba2a-11e4-9663-3950c8da14b0.png)

**Comment by mauimauer** [comment] 2015-02-21 23:53
I's day let's make the spinner dropdown white.

**Comment by tasomaniac** [comment] 2015-02-21 23:56
Removing that Spinner is also a good idea. :)

**Comment by mauimauer** [comment] 2015-02-21 23:57
@tasomaniac How would you choose a specific GDG then? I know that AB/TB Spinners are discouraged now...but I'd rather have it there than in the NavDrawer.

**Comment by tasomaniac** [comment] 2015-02-21 23:59
You set it when you first open the app. And then you can change it in the Settings. :)

**Comment by mauimauer** [comment] 2015-02-22 00:00
@tasomaniac uhm no...I know a lot of people who try to stay on top of the news and events of multiple GDGs in their region. That's why we have the Spinner AND a home GDG setting.

**Comment by HenriqueRocha** [comment] 2015-02-22 00:03
I will fix that as part of my new implementation of the new navigation
drawer.
On 22 Feb 2015 00:00, "Sebastian Mauer" <notifications@github.com> wrote:

> @tasomaniac <https://github.com/tasomaniac> uhm no...I know a lot of
> people who try to stay on top of the news and events of multiple GDGs in
> their region. That's why we have the Spinner AND a home GDG setting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdg-x/frisbee/issues/208#issuecomment-75402584>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by HenriqueRocha** [comment] 2015-02-22 00:20
Completely new implementation of the navigation drawer should be finished by next Sunday. I'll have to replace the action bar with the new toolbar and I'll take the time to fix the spinner too.

**Comment by friedger** [comment] 2015-02-22 07:53
What ever your urge is (I'll have to...) could you open an issue for that and explain what you would like to change? I like to see the toolbar but are there technical constraints for replacing action bar by toolbar? It could be fixed by changing the theme as in #210

**Comment by HenriqueRocha** [comment] 2015-02-22 08:01
It's not about urge. It's about the technical details of the action bar. The action bar belongs to the window so the navigation drawer can't be drawn on top of it and should be below the status bar. According to the new guidelines the navigation drawer should be on top of the action bar and that is not possible unless you use a toolbar.

**Comment by friedger** [comment] 2015-02-22 08:48
Ah, we have the issue already https://github.com/gdg-x/frisbee/issues/174

@HenriqueRocha Sorry, about my wording. It was meant as a funny comment. Just ignore it.

I understand now the motivation :+1: 
If the background of the navdrawer has the same background as the action bar I think that it meets the guidelines as well. To be continued at #174

**Comment by HenriqueRocha** [comment] 2015-02-26 22:26
Fixed with PR #230

**Closed by HenriqueRocha** 2015-02-26 22:26 UTC
