### ISSUE TITLE
Loading event details sometimes shows an error message.

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#473] opened 2015-08-14 21:48 UTC
This is for version 2.2.2

**Comment by tasomaniac** [comment] 2015-08-14 23:34
I think we have a problem with the hub Api. It gives a 404 for events. I
think syncing cron jobs are not working. Also the new events are not
synced. DevFest page should not be empty.

**Comment by tasomaniac** [comment] 2015-08-20 09:40
@Splaktar this issue is also really similar to the hub problems we've been talking about. It gives 404 error for events that we get through hub itself.

**Comment by tasomaniac** [comment] 2015-09-01 07:11
I can confirm that this is working as intended in the new hub deployment (http://146.148.62.106/). Closing this because it is automatically be fixed when the new hub IP is forwarded to hub.gdgx.io

**Closed by tasomaniac** 2015-09-01 07:11 UTC
Labels: bug
